// import { useEffect, useState } from 'react';
// import { testimonial_backend } from '../../../declarations/testimonial_backend'; // auto-generated by `dfx generate`

// const Testimonial = () => {
//   const [testimonials, setTestimonials] = useState([]);

//   useEffect(() => {
//     const fetchData = async () => {
//       try {
//         const result = await testimonial_backend.getTestimonials();
//         setTestimonials(result);
//       } catch (error) {
//         console.error("Failed to fetch testimonials:", error);
//       }
//     };

//     fetchData();
//   }, []);




import React from "react";
import Slider from "react-slick";
import { FaStar, FaStarHalfAlt, FaRegStar } from "react-icons/fa";
import { FaChevronLeft, FaChevronRight } from "react-icons/fa6";
import "./Testimonial.scss";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import img from '../../Images/mahila.png';
import image1 from '../../Images/bl1.jpg';

const testimonials = [
  {
    name: "Jane Doe",
    profession: "Product Manager",
    comment: "This platform exceeded my expectations. The interface is intuitive and the service is reliable.",
    rating: 4.5,
    imgSrc: img,
  },
  {
    name: "John Smith",
    profession: "Software Engineer",
    comment: "A seamless experience from start to finish. Highly recommend!",
    rating: 5,
    imgSrc: img,
  },
  {
    name: "Sarah Lee",
    profession: "UX Designer",
    comment: "Excellent support and a very smooth verification process. Kudos to the team!",
    rating: 4,
    imgSrc: image1,
  },
  {
    name: "Jane Doe",
    profession: "Product Manager",
    comment: "This platform exceeded my expectations. The interface is intuitive and the service is reliable.",
    rating: 4.5,
    imgSrc: image1,
  },
  {
    name: "John Smith",
    profession: "Software Engineer",
    comment: "A seamless experience from start to finish. Highly recommend!",
    rating: 5,
    imgSrc: image1,
  },
  {
    name: "Sarah Lee",
    profession: "UX Designer",
    comment: "Excellent support and a very smooth verification process. Kudos to the team!",
    rating: 4,
    imgSrc: image1,
  },
];

// Custom Arrow Components
const PrevArrow = ({ onClick }) => (
  <div className="arrow prev" onClick={onClick}>
    <FaChevronLeft />
  </div>
);

const NextArrow = ({ onClick }) => (
  <div className="arrow next" onClick={onClick}>
    <FaChevronRight />
  </div>
);

const Testimonial = () => {
  const settings = {
    dots: true,
    dotsClass: "slick-dots",
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 2,
    arrows: true,
    autoplay: true,
    cssEase: "linear",
    prevArrow: <PrevArrow />,
    nextArrow: <NextArrow />,
    responsive: [
      { breakpoint: 1200, settings: { slidesToShow: 3, slidesToScroll: 1, dots: false } },
      { breakpoint: 800, settings: { slidesToShow: 2, slidesToScroll: 1, dots: false } },
      { breakpoint: 600, settings: { slidesToShow: 1, slidesToScroll: 1, dots: false } }
    ]
  };

  const renderStars = (rating) => {
    const full = Math.floor(rating);
    const half = rating % 1 >= 0.5 ? 1 : 0;
    const empty = 5 - full - half;

    return (
      <>
        {Array(full).fill().map((_, i) => <FaStar key={`full-${i}`} className="star filled" />)}
        {half === 1 && <FaStarHalfAlt className="star filled" />}
        {Array(empty).fill().map((_, i) => <FaRegStar key={`empty-${i}`} className="star empty" />)}
      </>
    );
  };

  return (
    <section className="testimonial-section">
      <div className="testimonial-content">
        <h3 className="subtitle">What People Are Saying</h3>
        <h2 className="title">Real Voices, Real Experiences</h2>
        <p className="description">
          Hear directly from those who’ve benefited from our platform. Their stories of trust, value, and success reflect our commitment to excellence and innovation.
        </p>
      </div>

      <div className="testimonial-container">
        <Slider {...settings}>
          {testimonials.map((item, i) => (
            <div key={i}>
              <div className={`testimonial-card ${i % 2 === 0 ? "shadow1" : "shadow2"}`}>
                <div className="profile-img">
                  <img src={item.imgSrc} alt={item.name} />
                </div>
                <p className="comment">"{item.comment}"</p>
                <div className="info">
                  <div className="details">
                    <h3 className="name">{item.name}</h3>
                    <p className="profession">{item.profession}</p>
                  </div>
                  <div className="stars">{renderStars(item.rating)}</div>
                </div>
              </div>
            </div>
          ))}
        </Slider>
      </div>
    </section>
  );
};

export default Testimonial;
